version: "3"

services:
  postgres:
    image: postgres@sha256:311136771dca6826c3b6e691ebf8cb6e896e165074bc57a728f9619f25f0c4c7
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  broker_app:
    image: dius/pact-broker@sha256:16b7fce5e61f91435e06163add2a63662a69d74ae124bba8aadd6117f6a67e51
    links:
      - postgres
    ports:
      - 80:80
    environment:
      PACT_BROKER_BASIC_AUTH_USERNAME: pact_broker
      PACT_BROKER_BASIC_AUTH_PASSWORD: pact_broker
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres