name: SmartBear Supported Issue Label Added

on:
  issues:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pactflow/.github/.github/workflows/smartbear-issue-label-added.yml@5cab2ffe4451a4050cac41aecdfa1a1f52863783 # main
    secrets: inherit
