name: SmartBear Supported Issue Label Added

on:
  issues:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pactflow/.github/.github/workflows/smartbear-issue-label-added.yml@5c4363b8814c0149f87b9f9ded292f1f869302ff # main
    secrets: inherit
