name: SmartBear Supported Issue Label Added

on:
  issues:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pactflow/.github/.github/workflows/smartbear-issue-label-added.yml@4bd14637e98972c6ee1f7963a749035f89166283 # main
    secrets: inherit
